In [3]:
import pandas as pd
import numpy as np

# NumPy

## Arrays

In [ ]:
l1 = [1,2,3,4,5]
npa1=np.array(l1)
npa1

array([1, 2, 3, 4, 5])

### Create Array in Range


In [10]:
npa1=np.arange(1,5)
print(npa1)

#With steps increment
npa2=np.arange(1,5,2)
print(npa2)


[1 2 3 4]
[1 3]


## Matrix


In [ ]:
#How to define a matrix

#Directly declare the matrix as a 2D array list
mat1=np.array([[1,2,3],[4,5,6],[7,8,9]])
mat1






array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])