In [31]:
import pandas as pd
import numpy as np

# NumPy

## Arrays

In [32]:
l1 = [1,2,3,4,5]
npa1=np.array(l1)
npa1

array([1, 2, 3, 4, 5])

### Create Array in Range


In [33]:
npa1=np.arange(1,5)
print(npa1)

#With steps increment
npa2=np.arange(1,5,2)
print(npa2)


[1 2 3 4]
[1 3]


## Matrix


In [34]:
#How to define a matrix

#Directly declare the matrix as a 2D array list
mat1=np.array([[1,2,3],[4,5,6],[7,8,9]])
mat1

#Create a 3x3 matrix with random float values
mat2= np.random.rand(3,3)
mat2

#Create a 3x3 matrix with random int values
mat3= np.random.randint(0,40,(3,3))
mat3

#Create matrix filled with Zeros
mat4=np.zeros((3,3))
mat4

#Create matrix filled with Ones
mat5=np.ones((3,3))
mat5

#Create identity matrix
mat6=np.eye((5))
mat6

#Create matrix filled with specified value
mat7=np.full((3,3),7)
mat7



array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

## Generate Defined Number of Values within a range

In [39]:
val1=np.linspace(1,10,3)
val1

array([ 1. ,  5.5, 10. ])

In [ ]:
                        result = self.model.transcribe(
                            audio_data, language='en')
                        if result['text'].strip():